# Generated by Django 5.2.8 on 2025-12-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CheckoutItem',
        ),
    ]
